spring:
  mvc:
    cors:
      allowed-origins: http://localhost:4200,http://host.docker.internal:4200
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
  cors:
    allowed-origins: http://localhost:4200,http://localhost,http://host.docker.internal:4200
  datasource:
    url: jdbc:postgresql://postgres:5432/Medding
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.springframework.orm.jpa: DEBUG
