spring:
  mvc:
    cors:
      allowed-origins: http://localhost:4200,http://host.docker.internal:4200
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
  cors:
    allowed-origins: http://localhost:4200,http://localhost,http://host.docker.internal:4200
  datasource:
    url: jdbc:postgresql://postgres:5432/medding
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hikari:
      initialization-fail-timeout: 60000
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    host: smtp.gmail.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: 587

jwt:
  secret: NWYzYzQ3YjAzZDRmMmI0YjI1M2QwMjNiNWYzYzQ3YjAzZDRmMmI0YjI1M2QwMjNiNWYzYzQ3YjA=
  expiration: 86400000

logging:
  level:
    org.springframework.orm.jpa: DEBUG
